import glamorous from 'glamorous-native'

export { default as colors } from './src/colors'
export { default as fonts, fontMaps } from './src/fonts'
export { default as fontello } from './src/fontello'
export { default as Icon } from './src/Icon.component'
export { default as ImageBackground } from './src/ImageBackground.component'
export { default as DoubleCircle } from './src/DoubleCircle.component'
export * from './src/Text.component'
export * from './src/View.component'
