export { default as colors } from './colors'
export { default as fonts, fontMaps } from './fonts'
export { default as fontello } from './fontello'
export { default as Icon } from './Icon.component'
export { default as DoubleCircle } from './DoubleCircle.component'
export * from './Text.component'
export * from './View.component'
